# -*- coding: utf-8 -*-
"""intro_to_pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/mlcc/intro_to_pandas.ipynb
"""

import pandas as pd

orders = pd.read_csv("olist_orders_dataset.csv")
items = pd.read_csv("olist_order_items_dataset.csv")
customers = pd.read_csv("olist_customers_dataset.csv")
products = pd.read_csv("olist_products_dataset.csv")
reviews = pd.read_csv("olist_order_reviews_dataset.csv")
translation = pd.read_csv("product_category_name_translation.csv")

for name, df in zip(['orders','items','customers','products','reviews','translation'],
                    [orders, items, customers, products, reviews, translation]):
    print(f"\n--- {name} ---")
    print(df.isnull().sum())

orders = orders.dropna(subset=['order_approved_at'])
#Drops every cancelled order

products['product_category_name'] = products['product_category_name'].fillna('unknown')
#fills blank products with unknown
#product_category_name         610
#product_name_lenght           610
#product_description_lenght    610
#product_photos_qty            610
#Since all of these share the same "trait" i also have to replace the nulls
products['product_name_lenght'] = products['product_name_lenght'].fillna(0)
products['product_description_lenght'] = products['product_description_lenght'].fillna(0)
products['product_photos_qty'] = products['product_photos_qty'].fillna(0)

for col in ['product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']:
    products[col] = products[col].fillna(products[col].median())
#replaces null with median

reviews['review_comment_title'] = reviews['review_comment_title'].fillna('')
reviews['review_comment_message'] = reviews['review_comment_message'].fillna('')
#normal to not have reviews, replace it with "nothing"/empty space

for name, df in zip(['orders','items','customers','products','reviews','translation'],
                    [orders, items, customers, products, reviews, translation]):
    print(f"\n--- {name} ---")
    print(df.dtypes)

date_cols = ['order_purchase_timestamp', 'order_approved_at',
             'order_delivered_carrier_date', 'order_delivered_customer_date',
             'order_estimated_delivery_date']

for col in date_cols:
    orders[col] = pd.to_datetime(orders[col], errors='coerce')

items['shipping_limit_date'] = pd.to_datetime(items['shipping_limit_date'], errors='coerce')

reviews['review_creation_date'] = pd.to_datetime(reviews['review_creation_date'], errors='coerce')
reviews['review_answer_timestamp'] = pd.to_datetime(reviews['review_answer_timestamp'], errors='coerce')

orders = orders[orders['order_status'] == 'delivered']
print(f"Rows after filtering: {len(orders)}")

products = products.merge(translation, on='product_category_name', how='left')
#Add the english name column onto products

print(products[['product_category_name', 'product_category_name_english']].head(10))

print(f"\nNulls in english column: {products['product_category_name_english'].isnull().sum()}")

print(products[products['product_category_name_english'].isnull()]['product_category_name'].value_counts())
#shows theres 3 products that doesnt have a translation "Unknown" included

products['product_category_name_english'] = products['product_category_name_english'].fillna(
    products['product_category_name']
)
#Fills unknowns

products['product_category_name_english'] = products['product_category_name_english'].replace({
    'pc_gamer': 'pc_gamer',
    'portateis_cozinha_e_preparadores_de_alimentos': 'portable_kitchen_appliances'
})
#replaces the 2 products that did not have a name translated

print(products['product_category_name_english'].isnull().sum())

# delivery days — how long it took to deliver
orders['delivery_days'] = (
    orders['order_delivered_customer_date'] -
    orders['order_purchase_timestamp']
).dt.days

# is_late — was it delivered after the estimated date?
orders['is_late'] = (
    orders['order_delivered_customer_date'] >
    orders['order_estimated_delivery_date']
).astype(int)

# extract year and month for trend analysis
orders['order_year'] = orders['order_purchase_timestamp'].dt.year
orders['order_month'] = orders['order_purchase_timestamp'].dt.month

print(orders[['delivery_days', 'is_late', 'order_year', 'order_month']].head())
#Verify it works

# revenue per item
items['revenue'] = items['price'] + items['freight_value']
print(items[['price', 'freight_value', 'revenue']].head())
#verify it works

orders.to_csv("olist_orders_clean.csv", index=False, encoding='utf-8-sig')
items.to_csv("olist_items_clean.csv", index=False, encoding='utf-8-sig')
customers.to_csv("olist_customers_clean.csv", index=False, encoding='utf-8-sig')
products.to_csv("olist_products_clean.csv", index=False, encoding='utf-8-sig')
reviews.to_csv("olist_reviews_clean.csv", index=False, encoding='utf-8-sig')